sudo: required
language: python
cache: pip
python:
- '3.6'
env:
  global:
    - PIP_PROCESS_DEPENDENCY_LINKS=1
jobs:
  include:
  - stage: test
    install:
    - pip install pipenv
    - pipenv --python 3.6
    - pipenv install --dev --skip-lock
    script:
    - python3 -m flake8
  - stage: test
    before_install:
    - ./keycloak_demo/start-keycloak-demo.sh
    install:
    - pip install pipenv
    - pipenv --python 3.6
    - pipenv install --dev --skip-lock
    script:
    - pytest operations_api/tests

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  email: true
