sudo: required
language: python
cache: pip
python:
- '3.6'

jobs:
  include:
  - stage: test
    install:
    - pip install --user pipenv
    - pipenv --python 3.6
    - pipenv install --dev
    script:
    - python3 -m flake8


notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  email: true
